testthat::test_that("utils-file works well", {
    dir <- tempdir()
    dir.create(file.path(dir, "check_dir1"), recursive = TRUE)
    dir.create(file.path(dir, "check_dir2"), recursive = TRUE)
    file.create(file.path(dir, "check_file1"))
    file.create(file.path(dir, "check_file2"))
    testthat::expect_no_error(locate_file(dir, "^check_file1$"))
    testthat::expect_no_error(locate_file(dir, "^check_file2$"))
    testthat::expect_error(locate_file(dir, "^noneexist_file$"))
    testthat::expect_no_error(locate_files(dir))
    testthat::expect_no_error(locate_files(dir, "^check_file"))
    testthat::expect_error(locate_files(dir, "^noneexist_file$"))
    testthat::expect_no_error(locate_dir(dir, "^check_dir1$"))
    testthat::expect_no_error(locate_dir(dir, "^check_dir2$"))
    testthat::expect_error(locate_dir(dir, "^check_dir"))
    testthat::expect_error(locate_dir(dir, "^noneexist_directory$"))
})
